.PHONY: help

help:
	@echo "Kudora"
	@echo ""
	@echo "Business E2E (three validators)"
	@echo "  make e2e                  Run the complete suite"
	@echo "  make e2e-status           Show validator status"
	@echo "  make e2e-down             Stop the network"
	@echo ""
	@echo "Local development"
	@echo "  make localnet-up          Start the local validator"
	@echo "  make localnet-down        Stop it and keep its state"
	@echo "  make localnet-reset       Delete its local state"
	@echo "  make explorers-up         Start Blockscout and Ping"
	@echo "  make monitoring-up        Start Prometheus and Grafana"
	@echo ""
	@echo "Release"
	@echo "  make mainnet-genesis-build"
	@echo "  make mainnet-genesis-validate"
	@echo "  make release-package"
	@echo "  make release-verify"
	@echo "  make cosmovisor-smoke-test"
	@echo ""
	@echo "Development"
	@echo "  make build | docker-build | lint | tidy"
