// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kudora/discussion/v1/discussion.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Reaction is the single current opinion an account has on a message.
type Reaction int32

const (
	Reaction_REACTION_UNSPECIFIED Reaction = 0
	Reaction_REACTION_USEFUL      Reaction = 1
	Reaction_REACTION_NOT_USEFUL  Reaction = 2
)

var Reaction_name = map[int32]string{
	0: "REACTION_UNSPECIFIED",
	1: "REACTION_USEFUL",
	2: "REACTION_NOT_USEFUL",
}

var Reaction_value = map[string]int32{
	"REACTION_UNSPECIFIED": 0,
	"REACTION_USEFUL":      1,
	"REACTION_NOT_USEFUL":  2,
}

func (x Reaction) String() string {
	return proto.EnumName(Reaction_name, int32(x))
}

func (Reaction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e8f5d0d57fe01159, []int{0}
}

// StoredMessage is the compact value stored under message/{proposal_id}/{message_id}.
type StoredMessage struct {
	Author    []byte `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	ParentId  uint64 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Content   []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *StoredMessage) Reset()         { *m = StoredMessage{} }
func (m *StoredMessage) String() string { return proto.CompactTextString(m) }
func (*StoredMessage) ProtoMessage()    {}
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5d0d57fe01159, []int{0}
}
func (m *StoredMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredMessage.Merge(m, src)
}
func (m *StoredMessage) XXX_Size() int {
	return m.Size()
}
func (m *StoredMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StoredMessage proto.InternalMessageInfo

func (m *StoredMessage) GetAuthor() []byte {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *StoredMessage) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *StoredMessage) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *StoredMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// Message adds the key fields needed by query clients to a stored message.
type Message struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	MessageId  uint64 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Author     []byte `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	ParentId   uint64 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt  int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Content    []byte `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5d0d57fe01159, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *Message) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Message) GetAuthor() []byte {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Message) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Message) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// ReactionEntry is a query and genesis view of one canonical reaction entry.
type ReactionEntry struct {
	ProposalId uint64   `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	MessageId  uint64   `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Account    []byte   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Reaction   Reaction `protobuf:"varint,4,opt,name=reaction,proto3,enum=kudora.discussion.v1.Reaction" json:"reaction,omitempty"`
}

func (m *ReactionEntry) Reset()         { *m = ReactionEntry{} }
func (m *ReactionEntry) String() string { return proto.CompactTextString(m) }
func (*ReactionEntry) ProtoMessage()    {}
func (*ReactionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5d0d57fe01159, []int{2}
}
func (m *ReactionEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReactionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReactionEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReactionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReactionEntry.Merge(m, src)
}
func (m *ReactionEntry) XXX_Size() int {
	return m.Size()
}
func (m *ReactionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReactionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReactionEntry proto.InternalMessageInfo

func (m *ReactionEntry) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *ReactionEntry) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *ReactionEntry) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *ReactionEntry) GetReaction() Reaction {
	if m != nil {
		return m.Reaction
	}
	return Reaction_REACTION_UNSPECIFIED
}

// StoredSession is the compact value stored under a session address.
type StoredSession struct {
	Owner     []byte `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ExpiresAt int64  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *StoredSession) Reset()         { *m = StoredSession{} }
func (m *StoredSession) String() string { return proto.CompactTextString(m) }
func (*StoredSession) ProtoMessage()    {}
func (*StoredSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5d0d57fe01159, []int{3}
}
func (m *StoredSession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredSession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredSession.Merge(m, src)
}
func (m *StoredSession) XXX_Size() int {
	return m.Size()
}
func (m *StoredSession) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredSession.DiscardUnknown(m)
}

var xxx_messageInfo_StoredSession proto.InternalMessageInfo

func (m *StoredSession) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *StoredSession) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

// Session adds the session-address key needed by query and genesis clients.
type Session struct {
	Session   []byte `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Owner     []byte `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ExpiresAt int64  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f5d0d57fe01159, []int{4}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Session.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return m.Size()
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetSession() []byte {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Session) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Session) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("kudora.discussion.v1.Reaction", Reaction_name, Reaction_value)
	proto.RegisterType((*StoredMessage)(nil), "kudora.discussion.v1.StoredMessage")
	proto.RegisterType((*Message)(nil), "kudora.discussion.v1.Message")
	proto.RegisterType((*ReactionEntry)(nil), "kudora.discussion.v1.ReactionEntry")
	proto.RegisterType((*StoredSession)(nil), "kudora.discussion.v1.StoredSession")
	proto.RegisterType((*Session)(nil), "kudora.discussion.v1.Session")
}

func init() {
	proto.RegisterFile("kudora/discussion/v1/discussion.proto", fileDescriptor_e8f5d0d57fe01159)
}

var fileDescriptor_e8f5d0d57fe01159 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb3, 0x49, 0x1a, 0x27, 0x03, 0x85, 0x6a, 0x1b, 0xc1, 0x4a, 0x08, 0x13, 0x45, 0x42,
	0x8a, 0x90, 0xb0, 0x29, 0xdc, 0xb8, 0x85, 0xd6, 0x95, 0x0c, 0x25, 0x45, 0x76, 0x2b, 0x21, 0x2e,
	0xd1, 0xc6, 0x5e, 0xb5, 0x16, 0x74, 0xd7, 0xda, 0x5d, 0x97, 0xf6, 0xc0, 0x3b, 0xf0, 0x12, 0x3c,
	0x03, 0xaf, 0xc0, 0xb1, 0x47, 0x8e, 0x28, 0x79, 0x11, 0x14, 0x7b, 0xb7, 0x31, 0x88, 0xe6, 0xc2,
	0xcd, 0xff, 0x3f, 0xe3, 0x99, 0x6f, 0x67, 0x34, 0xf0, 0xf8, 0x63, 0x91, 0x0a, 0x49, 0xfd, 0x34,
	0x53, 0x49, 0xa1, 0x54, 0x26, 0xb8, 0x7f, 0xbe, 0x53, 0x53, 0x5e, 0x2e, 0x85, 0x16, 0xb8, 0x5f,
	0xa5, 0x79, 0xb5, 0xc0, 0xf9, 0xce, 0xf0, 0x0b, 0x6c, 0xc6, 0x5a, 0x48, 0x96, 0xbe, 0x65, 0x4a,
	0xd1, 0x13, 0x86, 0xef, 0x41, 0x87, 0x16, 0xfa, 0x54, 0x48, 0x82, 0x06, 0x68, 0x74, 0x3b, 0x32,
	0x0a, 0x3f, 0x80, 0x5e, 0x4e, 0x25, 0xe3, 0x7a, 0x9a, 0xa5, 0xa4, 0x39, 0x40, 0xa3, 0x76, 0xd4,
	0xad, 0x8c, 0x30, 0xc5, 0x0f, 0x01, 0x12, 0xc9, 0xa8, 0x66, 0xe9, 0x94, 0x6a, 0xd2, 0x1a, 0xa0,
	0x51, 0x2b, 0xea, 0x19, 0x67, 0xac, 0x31, 0x01, 0x27, 0x11, 0x5c, 0x33, 0xae, 0x49, 0xbb, 0x2c,
	0x6a, 0xe5, 0xf0, 0x3b, 0x02, 0xc7, 0x76, 0x7e, 0x04, 0xb7, 0x72, 0x29, 0x72, 0xa1, 0xe8, 0xa7,
	0x65, 0x0f, 0x54, 0xf6, 0x00, 0x6b, 0x55, 0x5d, 0xce, 0xaa, 0xdc, 0x15, 0x43, 0xcf, 0x38, 0x61,
	0x5a, 0x23, 0x6f, 0xdd, 0x4c, 0xde, 0x5e, 0x4b, 0xbe, 0xb1, 0x86, 0xbc, 0xf3, 0x27, 0xf9, 0x37,
	0x04, 0x9b, 0x11, 0xa3, 0x89, 0xce, 0x04, 0x0f, 0xb8, 0x96, 0x97, 0xff, 0xcd, 0x4f, 0xc0, 0xa1,
	0x49, 0x22, 0x0a, 0xae, 0xcd, 0x03, 0xac, 0xc4, 0x2f, 0xa1, 0x2b, 0x4d, 0xab, 0xf2, 0x01, 0x77,
	0x9e, 0xbb, 0xde, 0xbf, 0xb6, 0xe9, 0x59, 0xa0, 0xe8, 0x3a, 0x7f, 0xb8, 0x67, 0x17, 0x1c, 0xb3,
	0x32, 0x0d, 0xf7, 0x61, 0x43, 0x7c, 0xe6, 0xcc, 0xee, 0xb7, 0x12, 0x4b, 0x36, 0x76, 0x91, 0x67,
	0x92, 0xa9, 0xe5, 0x1c, 0x9a, 0xd5, 0x1c, 0x8c, 0x33, 0xd6, 0xc3, 0xf7, 0xe0, 0xd8, 0xff, 0x09,
	0x38, 0xaa, 0xfa, 0x34, 0x15, 0xac, 0x5c, 0x55, 0x6e, 0xde, 0x5c, 0xb9, 0xf5, 0x57, 0xe5, 0x27,
	0x11, 0x74, 0x2d, 0x35, 0x26, 0xd0, 0x8f, 0x82, 0xf1, 0xee, 0x51, 0x78, 0x38, 0x99, 0x1e, 0x4f,
	0xe2, 0x77, 0xc1, 0x6e, 0xb8, 0x1f, 0x06, 0x7b, 0x5b, 0x0d, 0xbc, 0x0d, 0x77, 0x57, 0x91, 0x38,
	0xd8, 0x3f, 0x3e, 0xd8, 0x42, 0xf8, 0x3e, 0x6c, 0x5f, 0x9b, 0x93, 0xc3, 0x23, 0x1b, 0x68, 0xbe,
	0x7a, 0xfd, 0x63, 0xee, 0xa2, 0xab, 0xb9, 0x8b, 0x7e, 0xcd, 0x5d, 0xf4, 0x75, 0xe1, 0x36, 0xae,
	0x16, 0x6e, 0xe3, 0xe7, 0xc2, 0x6d, 0x7c, 0x78, 0x76, 0x92, 0xe9, 0xd3, 0x62, 0xe6, 0x25, 0xe2,
	0xcc, 0x7f, 0x53, 0x4e, 0xf0, 0xe9, 0x01, 0x9d, 0x29, 0xdf, 0x9c, 0xd0, 0x45, 0xfd, 0x88, 0xf4,
	0x65, 0xce, 0xd4, 0xac, 0x53, 0x5e, 0xcf, 0x8b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x8d,
	0x8f, 0x6d, 0x66, 0x03, 0x00, 0x00,
}

func (m *StoredMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x22
	}
	if m.CreatedAt != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x18
	}
	if m.ParentId != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.ParentId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x32
	}
	if m.CreatedAt != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.ParentId != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.ParentId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MessageId != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.MessageId))
		i--
		dAtA[i] = 0x10
	}
	if m.ProposalId != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReactionEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReactionEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReactionEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reaction != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.Reaction))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MessageId != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.MessageId))
		i--
		dAtA[i] = 0x10
	}
	if m.ProposalId != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StoredSession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredSession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredSession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Session) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Session) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Session) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAt != 0 {
		i = encodeVarintDiscussion(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Session) > 0 {
		i -= len(m.Session)
		copy(dAtA[i:], m.Session)
		i = encodeVarintDiscussion(dAtA, i, uint64(len(m.Session)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDiscussion(dAtA []byte, offset int, v uint64) int {
	offset -= sovDiscussion(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	if m.ParentId != 0 {
		n += 1 + sovDiscussion(uint64(m.ParentId))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovDiscussion(uint64(m.CreatedAt))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	return n
}

func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovDiscussion(uint64(m.ProposalId))
	}
	if m.MessageId != 0 {
		n += 1 + sovDiscussion(uint64(m.MessageId))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	if m.ParentId != 0 {
		n += 1 + sovDiscussion(uint64(m.ParentId))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovDiscussion(uint64(m.CreatedAt))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	return n
}

func (m *ReactionEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovDiscussion(uint64(m.ProposalId))
	}
	if m.MessageId != 0 {
		n += 1 + sovDiscussion(uint64(m.MessageId))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	if m.Reaction != 0 {
		n += 1 + sovDiscussion(uint64(m.Reaction))
	}
	return n
}

func (m *StoredSession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovDiscussion(uint64(m.ExpiresAt))
	}
	return n
}

func (m *Session) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Session)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDiscussion(uint64(l))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovDiscussion(uint64(m.ExpiresAt))
	}
	return n
}

func sovDiscussion(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDiscussion(x uint64) (n int) {
	return sovDiscussion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiscussion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = append(m.Author[:0], dAtA[iNdEx:postIndex]...)
			if m.Author == nil {
				m.Author = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentId", wireType)
			}
			m.ParentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content[:0], dAtA[iNdEx:postIndex]...)
			if m.Content == nil {
				m.Content = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDiscussion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiscussion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiscussion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			m.MessageId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = append(m.Author[:0], dAtA[iNdEx:postIndex]...)
			if m.Author == nil {
				m.Author = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentId", wireType)
			}
			m.ParentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content[:0], dAtA[iNdEx:postIndex]...)
			if m.Content == nil {
				m.Content = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDiscussion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiscussion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReactionEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiscussion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReactionEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReactionEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			m.MessageId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = append(m.Account[:0], dAtA[iNdEx:postIndex]...)
			if m.Account == nil {
				m.Account = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reaction", wireType)
			}
			m.Reaction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reaction |= Reaction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDiscussion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiscussion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredSession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiscussion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredSession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredSession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDiscussion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiscussion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Session) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDiscussion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Session: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Session: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Session = append(m.Session[:0], dAtA[iNdEx:postIndex]...)
			if m.Session == nil {
				m.Session = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDiscussion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDiscussion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDiscussion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDiscussion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDiscussion(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDiscussion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDiscussion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDiscussion
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDiscussion
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDiscussion
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDiscussion        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDiscussion          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDiscussion = fmt.Errorf("proto: unexpected end of group")
)
