#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="${KUDORA_HOST_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "${ROOT_DIR}"

source "${ROOT_DIR}/scripts/release/common.sh"
source "${ROOT_DIR}/deploy/localnet/scripts/common.sh"

if [[ "${KUDORA_IN_DOCKER:-}" == "1" ]]; then
  COSMOVISOR_HOST_ADDRESS="${KUDORA_DOCKER_HOST_ALIAS:-host.docker.internal}"
else
  COSMOVISOR_HOST_ADDRESS="${KUDORA_HOST_ADDRESS:-127.0.0.1}"
fi

COSMOVISOR_DIR="${ROOT_DIR}/deploy/cosmovisor"
COSMOVISOR_COMPOSE_FILE="${COSMOVISOR_DIR}/docker-compose.yml"
COSMOVISOR_ENV_FILE="${COSMOVISOR_DIR}/env/cosmovisor.env.example"
COSMOVISOR_HOME_DIR="${RELEASE_COSMOVISOR_TMP_DIR}/home"
COSMOVISOR_RESULT_PATH="${RELEASE_COSMOVISOR_TMP_DIR}/result.json"
COSMOVISOR_LAYOUT_RESULT_PATH="${RELEASE_COSMOVISOR_TMP_DIR}/layout.json"
COSMOVISOR_LOG_DIR="${RELEASE_COSMOVISOR_TMP_DIR}/logs"
COSMOVISOR_CONTAINER_NAME="${COSMOVISOR_CONTAINER_NAME:-kudora-cosmovisor}"
COSMOVISOR_PROJECT_NAME="${COSMOVISOR_PROJECT_NAME:-kudora-cosmovisor}"
COSMOVISOR_RPC_URL="${COSMOVISOR_RPC_URL:-http://${COSMOVISOR_HOST_ADDRESS}:37657}"
COSMOVISOR_REST_URL="${COSMOVISOR_REST_URL:-http://${COSMOVISOR_HOST_ADDRESS}:11317}"
COSMOVISOR_GRPC_URL="${COSMOVISOR_GRPC_URL:-${COSMOVISOR_HOST_ADDRESS}:39090}"
COSMOVISOR_EVM_RPC_URL="${COSMOVISOR_EVM_RPC_URL:-http://${COSMOVISOR_HOST_ADDRESS}:9545}"
COSMOVISOR_EVM_WS_URL="${COSMOVISOR_EVM_WS_URL:-ws://${COSMOVISOR_HOST_ADDRESS}:9546}"
COSMOVISOR_HOST_UID="${LOCAL_UID:-$(id -u)}"
COSMOVISOR_HOST_GID="${LOCAL_GID:-$(id -g)}"
COSMOVISOR_RUNTIME_HOME="${COSMOVISOR_RUNTIME_HOME:-/kudora-home}"
COSMOVISOR_INIT_HOME="${COSMOVISOR_INIT_HOME:-${COSMOVISOR_RUNTIME_HOME}}"
COSMOVISOR_RUNTIME_USER="${COSMOVISOR_HOST_UID}:${COSMOVISOR_HOST_GID}"
COSMOVISOR_RELEASE_IMAGE_TAG="${KUDORA_RELEASE_DOCKER_IMAGE:-$(release_docker_image_tag)}"
COSMOVISOR_IMAGE_TAG="${KUDORA_COSMOVISOR_IMAGE:-$(release_cosmovisor_image_tag)}"
COSMOVISOR_DOCKER_PLATFORM="${COSMOVISOR_DOCKER_PLATFORM:-$(release_runtime_docker_platform)}"
COSMOVISOR_NETWORK="${COSMOVISOR_NETWORK:-kudora-cosmovisor}"
COSMOVISOR_VALIDATOR_KEY_NAME="phase17-cosmovisor-validator"

cosmovisor_die() {
  echo "$*" >&2
  exit 1
}

cosmovisor_prepare_dirs() {
  release_prepare_dirs
  mkdir -p "${COSMOVISOR_HOME_DIR}" "${COSMOVISOR_LOG_DIR}"
}

cosmovisor_run_release() {
  docker run --rm \
    --platform "${COSMOVISOR_DOCKER_PLATFORM}" \
    --user "${COSMOVISOR_RUNTIME_USER}" \
    -e HOME="${COSMOVISOR_INIT_HOME}" \
    -e TMPDIR=/tmp \
    -e XDG_CACHE_HOME=/tmp/.cache \
    -v "${COSMOVISOR_HOME_DIR}:${COSMOVISOR_INIT_HOME}" \
    "${COSMOVISOR_RELEASE_IMAGE_TAG}" "$@"
}

cosmovisor_compose() {
  require_compose
  COMPOSE_PROJECT_NAME="${COSMOVISOR_PROJECT_NAME}" \
  LOCAL_UID="${COSMOVISOR_HOST_UID}" \
  LOCAL_GID="${COSMOVISOR_HOST_GID}" \
  KUDORA_COSMOVISOR_IMAGE="${COSMOVISOR_IMAGE_TAG}" \
  COSMOVISOR_DOCKER_PLATFORM="${COSMOVISOR_DOCKER_PLATFORM}" \
  COSMOVISOR_HOME_HOST="${COSMOVISOR_HOME_DIR}" \
  COSMOVISOR_NETWORK="${COSMOVISOR_NETWORK}" \
  "${COMPOSE_CMD[@]}" -f "${COSMOVISOR_COMPOSE_FILE}" "$@"
}
